forge 'https://forge.puppet.com'
mod 'puppetlabs-puppetdb',    '7.8.0'
mod 'saz-sudo',    '6.0.0'
mod 'puppetlabs-stdlib',    '7.0.0'
mod 'puppetlabs-concat',    '7.0.1'
mod 'puppet-archive',    '4.6.0'
mod 'npt', git: 'https://github.com/puppetlabs/puppetlabs-ntp', tag: 'v9.0.1'
mod 'apt', git: 'https://github.com/puppetlabs/puppetlabs-apt', branch: 'main'
